name: MapDataInput
description: Map thing!
# version: 1.0.0
#author: max

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  path: ^1.4.1
  google_maps: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
